title: Espresso Aficionados
description: Info from the Espresso Aficionados Discord server

aux_links:
  "r/espresso on Reddit":
    "//www.reddit.com/r/espresso/"
  "Espresso Aficionados Discord":
    "//discord.gg/espresso"
aux_links_new_tab: true

remote_theme: pmarsceill/just-the-docs
color_scheme: "light"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true #
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/Espresso-Aficionados/website"
gh_edit_branch: "main"
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

plugins:
  - jekyll-remote-theme
